server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  h2:
    console:
      enabled: true

microservice:
  people:
    url: "http://localhost:8081/api/people"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      SQL: debug
